# Produce Win32 executables dependent on msvcrt.dll
AS=aswin
CC=gccwin
LD=ldwin
CFLAGS=-S -O2 -fno-common -ansi -I. -I../pdos/pdpclib -D__WIN32__ \
  -D__NOBIVA__ -DTARGET_AS386=1
# -DTARGET_AS386=1
OBJS=main.o

all: clean occ.exe

occ.exe: $(OBJS)
  $(LD) -s -o occ.exe ../pdos/pdpclib/w32start.o $(OBJS) ../pdos/pdpclib/msvcrt.a

.c.o:
  $(CC) $(CFLAGS) $<
  $(AS) -o $@ $*.s
  rm -f $*.s

clean:
  rm -f *.o occ.exe
